# version of docker compose
version: '3'

services: 
    redis-server:
        image: 'redis'
    node-app:
        # restart policies for what to do in case of crash , here we specified unless-stopped i.e always restart unless we foribly stop using cli
        restart: unless-stopped
        # look into the current folder and build the image uing that docker file
        build: .
        ports: 
            - "4000:8081"
            # 4000 is the port on local machine which connected to port 8081 in the container
            
